### PR TITLE
[Feature] Filter Extension

### PR DESCRIPTION
**Pull request by bblurock**
Hi, I added a filtering function to Extensity.

Extensity is very convenient until I installed tons of extensions that I have to search for a specific one to toggle.

I added an attribute in option page (which I let it to be toggled on by default).
screen shot 2015-04-03 at 11 52 07 pm

And when checked. A input box will be shown after header.
screen shot 2015-04-03 at 11 52 33 pm

Input string is compared with  extensions' names by using `underscore.string.include`. The unmatched extensions will be hidden.
screen shot 2015-04-03 at 11 53 06 pm

### CODE REVIEW

**Comment by sergiokas** [comment]
I like this idea in general. I'm currently reworking the popup for some performance improvements, but I'll definitely include this if possible in the next release

**Comment by a7madgamal** [comment]
I was just going to implement that :+1:

**Comment by sergiokas** [comment]
@a7madgamal closed in favor of pull/14, but the idea is there. I've added a styled filter box in the newest release (1.3.0). Thanks for contributing!

**Comment by a7madgamal** [comment]
awesome ❤️

**Pull request closed without merging**
